# Generated by Django 5.0.6 on 2025-06-20 15:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChiqimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EskiIsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.CharField(max_length=500, null=True)),
                ('sana', models.DateField(null=True)),
                ('narxi', models.IntegerField(null=True)),
                ('soni', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(null=True)),
                ('sana', models.DateField(auto_now_add=True, null=True)),
                ('narxi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('maosh', models.IntegerField()),
                ('telefon', models.CharField(max_length=15)),
                ('is_oylik_open', models.BooleanField(default=True, null=True)),
                ('oldingi_oylik', models.IntegerField(blank=True, default=0, null=True)),
                ('yangi_oylik', models.IntegerField(default=0, null=True)),
                ('oylik_yopilgan_sana', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(null=True)),
                ('sana', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_approve_ishrequest', 'Can approve work requests')],
            },
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('summa', models.PositiveIntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oyliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('oylik', models.IntegerField(null=True)),
                ('yopilgan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('telefon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olchov_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('gr', 'Gramm'), ('lt', 'Litr'), ('dona', 'Dona'), ('dm', 'detsimetr')], max_length=20)),
                ('minimal_miqdor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qabul_qilingan_sana', models.DateField(auto_now_add=True)),
                ('amal_qilish_muddati', models.DateField(blank=True, null=True)),
                ('holati', models.CharField(choices=[('active', 'Faol'), ('deactive', 'Nofaol'), ('expired', 'Muddati otgan')], max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XomashyoHarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakat_turi', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('inventarizatsiya', 'Inventarizatsiya'), ('qaytarish', 'Qaytarish')], max_length=20)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('izoh', models.TextField(blank=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('inn', models.CharField(blank=True, max_length=20)),
                ('qisqacha_tavsif', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('is_ishchi', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chiqimlar', to='main.chiqimturi')),
            ],
        ),
    ]
