# Generated by Django 5.0.6 on 2025-06-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ish',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='ishchi',
            name='eski_ishlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishchilar', to='main.eskiish'),
        ),
        migrations.AddField(
            model_name='ishchi',
            name='turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_turi', to='main.category'),
        ),
        migrations.AddField(
            model_name='ishchi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishchi_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ish',
            name='ishchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishlar', to='main.ishchi'),
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ishchi'),
        ),
        migrations.AddField(
            model_name='ishrequest',
            name='ishchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_requests', to='main.ishchi'),
        ),
        migrations.AddField(
            model_name='ishrequest',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='ishrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kirim',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='oyliklar',
            name='ishchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyliklar', to='main.ishchi'),
        ),
        migrations.AddField(
            model_name='oyliklar',
            name='ishlari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oylik_ishlari', to='main.eskiish'),
        ),
        migrations.AddField(
            model_name='ishchi',
            name='current_oylik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ishchi', to='main.oyliklar'),
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi_oylik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eski_ishlar', to='main.oyliklar'),
        ),
        migrations.AddField(
            model_name='xaridor',
            name='mahsuloti',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='kirim',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirimlar', to='main.xaridor'),
        ),
        migrations.AddField(
            model_name='xomashyoharakat',
            name='foydalanuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xomashyoharakat',
            name='xomashyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.xomashyo'),
        ),
        migrations.AddField(
            model_name='xomashyoharakat',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yetkazibberuvchi'),
        ),
        migrations.AddField(
            model_name='xomashyo',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yetkazibberuvchi'),
        ),
    ]
